### PR TITLE
Allow nested target paths in replace_attribute action

### PR DESCRIPTION
**Pull request by pkalita-lbl**
Required for https://github.com/microbiomedata/issues/issues/718, but keeping that issue open until the actual `submission-schema` changes are made.

### Summary

The main thing these changes aim to do is provide support for a line like this in the modifications TSV file, where the target of the `replace_attribute` action is a nested path:

| class | slot | action | target | value |
| --- | --- | --- | --- | --- |
| SoilInterface | env_local_scale | replace_attribute | any_of.0.range | EnvLocalScaleSoilEnum |

While I was at it I took the opportunity to a little overdue refactoring and testing.

### Details

* Moved the handlers for each action type into standalone functions that each take the same arguments. These are then grouped into a `dict`, keyed on the action name. While processing each row of the modification TSV, the appropriate action handler is retrieved from this map and called.
* Updated the handler for the `replace_attribute` action to accept nested paths. When one is encountered it builds out the necessary intermediate structures in the `schema_dict` before setting the `value`. See inline comments for more details. I also fixed a bug in this handler where strings were not being cast into booleans correctly. 
* Added a new action named `remove_attribute`.
* Added unit tests for each action handler function along with a new GitHub Actions workflow to run the unit tests on PRs and merges to `main`.
* Fixed the `poetry-dynamic-versioning` setup

### CODE REVIEW

**Review by turbomam — APPROVED** [review]

**Comment by mslarae13** [comment]
I tested a submission in dev & it isn't validating. Should this be live in dev & testable? @pkalita-lbl

**Comment by turbomam** [comment]
@mslarae13 can you please describe what you tried to do and the way in which it failed?

**Comment by pkalita-lbl** [comment]
Here's where we are right now:

✅  These changes made to `sheets_and_friends`
✅  New version of `sheets_and_friends` [released](https://pypi.org/project/sheets-and-friends/0.5.3/)
✅  New version of `sheets_and_friends` [used](https://github.com/microbiomedata/submission-schema/pull/200) in `submission-schema` build
✅  New version of `submission-schema` [released](https://pypi.org/project/nmdc-submission-schema/10.5.0/)
🚫 Bring new version of `submission-schema` into `nmdc-server`

**Comment by pkalita-lbl** [comment]
Yes I can let you know

**Pull request merged**
