### PR TITLE
add `pattern` property to generated NMDC linkml schema

### PR DESCRIPTION
**Pull request by sujaypatil96**
This PR seeks to address issue #104.

Approach:
The new `modifications_and_validation` entry point consumes the [validation_converter](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=928747012) sheet, and implements the validation rules logic that populates the schema with the `pattern` attribute in addition to the logic that works on the `modifications_long` sheet.

---

To test:

```
make all
```

### CODE REVIEW

**Comment by sujaypatil96** [comment]
@turbomam: this PR is ready for review.

**Comment by turbomam** [comment]
It looks like this was based on the main branch. I can see why you would have done that, but my intention is to use this new contribution in `issue-100-netlify-linkml-datastructure`

I have checked out `spatil/add-regex-validators` but can't do `make docs/template/nmdc_dh/schema.js`

>  make: *** No rule to make target 'docs/template/nmdc_dh/schema.js'.  Stop.

I locally merged `issue-100-netlify-linkml-datastructure` into `spatil/add-regex-validators` and ran 
`make docs/template/nmdc_dh/schema.js`

that completed and built a `docs/linkml.html`. I opened the `nmdc_dh/soil_emsl_jgi_mg` template and loaded the [sample data file](https://raw.githubusercontent.com/microbiomedata/sheets_and_friends/main/artifacts/for_data_harmonizer_template/exampleInput/soil_emsl_jgi_mg_example_data.tsv) and ran the validation

I couldn't get it to accept any values I tried in the `depth, meters` column, but it DOESN'T"T complain about non-CURIE values in `globally unique ID`

**Comment by turbomam** [comment]
I do see 

```json
"pattern": "^[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)? \\S+$"
```

for `depth` in `docs/template/nmdc_dh/schema.js`  Isn't that the rule for floats, not floats OR ranges of floats?

but I don't see any pattern for `source_mat_id` (which gets entitled "globally unique ID") Maybe something internal to LinkML handled that, since it's `identifier` attribute is set to true?

```JSON
        "source_mat_id": {
          "name": "source_mat_id",
          "rank": 1,
          "description": "A globally unique identifier assigned to the biological sample.",
          "title": "globally unique ID",
          "notes": [
            "The source material IS the Globally Unique ID"
          ],
          "comments": [
            "Identifiers must be prefixed. IGSNs (http://www.geosamples.org/getigsn) are unique and FAIR. UUIDs (https://www.uuidgenerator.net/) are globally unique but not FAIR. These IDs enable linking to derrived analytes and subsamples."
          ],
          "examples": [
            {
              "value": "IGSN:AU1243"
            }
          ],
          "from_schema": "http://w3id.org/mixs/terms",
          "is_a": "nucleic acid sequence source field",
          "string_serialization": "{text}:{text}",
          "slot_uri": "MIXS:0000026",
          "multivalued": false,
          "identifier": true,
          "owner": "MIMS",
          "slot_group": "Sample ID",
          "range": "string",
          "required": true,
          "recommended": true
        },
```

**Comment by turbomam** [comment]
It's not complaining about `pH` values of 999 either. But that's not a regex validation.

**Comment by turbomam** [comment]
`sample shipped amount` looks goo: requires a float followed by some text (for the unit)

**Review by turbomam — APPROVED** [review]

**Pull request merged**
